### ISSUE TITLE
API Spec Booking object

### ISSUE THREAD

**Issue by dkmonaghan** [sem5640-2018/booking-facilities#5]
The swagger.json file submitted (which I approved and merged before I noticed, whoops, sorry) describes a Booking object.

The "venue" and "courtName" fields are both free text strings here. Should one of them not be the ID of a "facility"? 

Are we having the concept of a "facility" object, seeing as administrators will be able to add/remove/change "facilities"? If so, it would make more sense for a Booking object to reference a Facility object by ID.

**Comment by RobertMouncer** [comment]
This is something we missed and have been discussing this afternoon. We'll post a proposal here later today of how the objects are linked. We were thinking of something like this:
![untitled diagram](https://user-images.githubusercontent.com/44447819/47953220-81b21e80-df72-11e8-8415-e4538c5a146d.png)

It gives the admin the ability to perform CRUD operations on the facilities, sports and courts as well as providing booking functionality for the micro-service and ladder. The response objects from the API will differ a lot from what had previously be proposed. 

Regarding the second issue, yes it should take a facility and a sport. This will be changed later today.

**Comment by dkmonaghan** [comment]
Hm, is having both 'Courts' and 'Facilities' redundant? Could a court just count as a facility? While they might be housed in the same building, I don't see an advantage to having objects representing a building. Things such as 'swimming pool' would also be poorly represented by the word 'court' and would better suit a 'facility'. 

Also, is the SportCourts table required? What's it's purpose?

**Comment by dkmonaghan** [comment]
Hm, okay. I see what you're getting at now, my bad.

Perhaps renaming 'facilities' to 'Venues' is a better idea then? I'm not sure what we rename 'courts' to at the moment, perhaps ask in the Slack to see if anyone has any ideas. 

Poor wording on my behalf - what I meant was - where does the SportsCourts table actually get used? Is it meant to provide restrictions on what activities can be booked in which 'courts'? e.g to prevent someone booking a swimming activity on a tennis court? So we 'whitelist' which activities are allowed on which courts, essentially?

**Comment by RobertMouncer** [comment]
"Venues" is a good name.
"Sport" should be fine.
We've slack the word to replace "court".

Yes exactly. It defines which courts can be used for which sports and vice-versa. This would be set-up by the administrator when they are in the Bookings service.

We'll make changes to the swagger doc tonight.

**Comment by RobertMouncer** [comment]
Re: your edit.
Yes that's correct and also returns available times.
