### ISSUE TITLE
Facility Blocks have a Sport associated with them

### ISSUE THREAD

**Issue by dkmonaghan** [sem5640-2018/booking-facilities#73]
Can we hide this from the UI? I've hidden it from the Index table, but it also needs removing from the 'Create Facility Block' page. I've removed the dropdown from the 'EditBlockFacility' view too, just the 'Create' needs handling.

Can't remove it from 'Create' as the Model requires that a sport be specified (I think?).

**Comment by RobertMouncer** [comment]
@dkmonaghan sports needs to be specified for a facility block. A facility, for example court 1,, is defined by where it is (venue) and what sport it is used for. It needs to remain in the editBlockFacility view and the create page.

**Comment by RobertMouncer** [comment]
It also needs to be available on the index page as two facilities for two different sports could be called "Court 1"

**Comment by dkmonaghan** [comment]
https://img.dan-lab.net/2018-12/9e1703c4-8077-460a-b89c-0a406fa3966d.png
